[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/myrequests"
  to = "/myrequests/index.html"
  status = 200

[[redirects]]
  from = "/handlerequests"
  to = "/handlerequests/index.html"
  status = 200

[[redirects]]
  from = "/users"
  to = "/users/index.html"
  status = 200

[[redirects]]
  from = "/verifyemailsent"
  to = "/verifyemailsent/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login/index.html"
  status = 200

[[redirects]]
  from = "/reset"
  to = "/reset/index.html"
  status = 200

[[redirects]]
  from = "/register"
  to = "/register/index.html"
  status = 200
